apiVersion: v1
entries:
  opentelemetry-demo:
  - apiVersion: v2
    appVersion: 2.0.2
    created: "2025-05-10T16:14:31.452615+05:30"
    dependencies:
    - condition: opentelemetry-collector.enabled
      name: opentelemetry-collector
      repository: https://open-telemetry.github.io/opentelemetry-helm-charts
      version: 0.117.1
    - condition: jaeger.enabled
      name: jaeger
      repository: https://jaegertracing.github.io/helm-charts
      version: 3.4.0
    - condition: prometheus.enabled
      name: prometheus
      repository: https://prometheus-community.github.io/helm-charts
      version: 27.4.0
    - condition: grafana.enabled
      name: grafana
      repository: https://grafana.github.io/helm-charts
      version: 8.10.1
    - condition: opensearch.enabled
      name: opensearch
      repository: https://opensearch-project.github.io/helm-charts
      version: 2.31.0
    description: opentelemetry demo helm chart
    digest: b482124e57192210f35b31e67a89b3b7972b2ee4f989a2f82489f739a3a83f7f
    home: https://opentelemetry.io/
    icon: https://opentelemetry.io/img/logos/opentelemetry-logo-nav.png
    maintainers:
    - name: dmitryax
    - name: jaronoff97
    - name: puckpuck
    - name: tylerhelmuth
    name: opentelemetry-demo
    sources:
    - https://github.com/open-telemetry/opentelemetry-demo
    type: application
    urls:
    - https://migrateai.github.io/opentelemetry-helm-charts/charts/opentelemetry-demo-0.37.5.tgz
    version: 0.37.5
generated: "2025-05-10T16:14:31.42766+05:30"
